const missionConditions = [
  { id: 'no-stunts', label: 'Perform no stunts in a single race', avoidJumps: true },
  { id: 'no-jumps', label: 'Perform no jumps in a single race', avoidJumps: true },
  { id: 'no-barrel-rolls', label: 'Perform no barrel rolls in a single race', avoidJumps: true },
  { id: 'jumps', label: 'Perform X jumps in a single race', needsJumps: true },
  { id: 'stunts', label: 'Perform X stunts in a single race', needsJumps: true },
  { id: 'barrel-rolls', label: 'Perform X barrel rolls in a single race', needsJumps: true },
  { id: 'air-time', label: 'Perform Xs of air time in a single race', needsJumps: true },
  { id: 'nitro-time', label: 'Perform Xs of nitro time in a single race' },
  { id: 'drift-meters', label: 'Drift X meters in a single race' },
  { id: 'drive-meters', label: 'Drive X meters total' },
  { id: 'perfect-runs', label: 'Perform X perfect runs in a single race' },
  { id: '360-knockdowns', label: 'Perform X 360 knockdowns in a single race', needsJumps: true },
  { id: 'first-place', label: 'Finish in first place X times' },
  { id: 'top-3', label: 'Reach top 3 in X races' },
  { id: 'finish-races', label: 'Finish X races' },
  { id: 'shockwave-knockdowns', label: 'Get X shockwave knockdowns' },
  { id: 'knockdowns', label: 'Perform X knockdowns' },
  { id: 'fewer-objects', label: 'Destroy X or fewer objects in a single race' },
  { id: 'fewer-nitro', label: 'Collect X or fewer nitro bottles in a single race' },
  { id: 'buy-items', label: 'Buy X items in the Legend Store' },
  { id: 'open-packs', label: 'Open X card packs' },
  { id: 'import-parts', label: 'Apply X import parts' },
  { id: 'star-up', label: 'Star up any cars' }
];
